import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import Script from "next/script";
import GoogleAdsense from "./adsense";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <meta
        name="google-adsense-account"
        content="ca-pub-3195296029072717"
      />
      <GoogleAdsense pId="3195296029072717" />
    </head>
      <body className={`${inter.className} dark`}>
        {children}
        <Analytics />
        
      </body>
    </html>
  );
}
